### PR TITLE
Added Resource page

### PR DESCRIPTION
**Pull request by mellofordev**
1.Implemented active link colors
2.Added resource page which fetches
resource site image and title by creating api

### CODE REVIEW

**Comment by aswnss-m** [comment]
@mellofordev I'm getting the cross reference error while fetching the image using w3 API

`Access to fetch at 'https://4w1jwm.deta.dev/https://w3schools.com/' from origin 'http://localhost:5174' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Review by aswnss-m — CHANGES_REQUESTED** [review]
CORS error

**Comment by mellofordev** [comment]
Ok so the problem is my port number is 5173 and your's is 5174 
I added origin for my port number in backend 
Will fix it now

**Comment by mellofordev** [comment]
@aswnss-m  fixed the cors issue (added your port number 5174 to backend)
please try again

**Review by aswnss-m — APPROVED** [review]

**Pull request merged**
